export const UPDATE_SEARCH_AREAS = '@search/UPDATE_SEARCH_AREAS';
export const UPDATE_SEARCH_INGREDIENTS = '@search/UPDATE_SEARCH_INGREDIENTS';
export const UPDATE_SEARCH_LOADING = '@search/UPDATE_SEARCH_LOADING';
export const UPDATE_SEARCH_LIST = '@search/UPDATE_SEARCH_LIST';
export const UPDATE_SEARCH_FORMDATA = '@search/UPDATE_SEARCH_FORMDATA';
export const UPDATE_SEARCH_ITEM = '@search/UPDATE_SEARCH_ITEM';
